services:
  db:
    image: postgres:16-bookworm
    container_name: innercircle_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - innercircle_network

  web:
    build: .
    container_name: innercircle_app
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 --workers 4 --timeout 120 mysite.wsgi:application"
    environment:
      - CSRF_TRUSTED_ORIGINS=https://sergiodaw2.tech,https://www.sergiodaw2.tech
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
    ports:
      - "8000:8000"
    volumes:
      - ./proyecto_final:/app:delegated
      - static_volume:/app/staticfiles
      - ./proyecto_final/media:/app/media:delegated
    depends_on:
      db:
        condition: service_healthy
    networks:
      - innercircle_network

  nginx:
    image: nginx:alpine
    container_name: innercircle_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles:ro
      - ./proyecto_final/media:/app/media:ro
      - ./fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./privkey.pem:/etc/nginx/certs/privkey.pem:ro
    depends_on:
      - web
    networks:
      - innercircle_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  innercircle_network:
    driver: bridge
