# Generated by Django 6.0.4 on 2026-04-24 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner_circle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='escritor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escritor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resena',
            name='recibidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recibidor', to=settings.AUTH_USER_MODEL),
        ),
    ]
