# Generated by Django 6.0.4 on 2026-04-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner_circle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(default=9999999),
            preserve_default=False,
        ),
    ]
