# Generated by Django 6.0.4 on 2026-04-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner_circle', '0002_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_prod',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img_perfil',
            field=models.ImageField(upload_to='profiles/'),
        ),
    ]
