# Generated by Django 6.0.4 on 2026-05-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner_circle', '0003_venta_stripe_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
