# Generated by Django 6.0.4 on 2026-04-27 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner_circle', '0004_remove_mensaje_producto_remove_mensaje_receptor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensaje', 'Nuevo mensaje'), ('venta', 'Nueva venta'), ('resena', 'Nueva reseña'), ('amistad', 'Solicitud de amistad')], max_length=20)),
                ('contenido', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
