# Generated by Django 6.0.4 on 2026-04-21 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner_circle', '0004_alter_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendiente', 'pendiente'), ('aceptada', 'aceptada'), ('rechazada', 'rechazada')], default='pendiente')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recibidor2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibe_solicitud', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envia_solicitud', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
