# Generated by Django 6.0.4 on 2026-05-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner_circle', '0004_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
