# Generated by Django 6.0.4 on 2026-05-01 14:02

import django.core.validators
import inner_circle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner_circle', '0005_user_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_rate_limit_warning',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_prod',
            field=models.ImageField(upload_to='products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif']), inner_circle.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img_perfil',
            field=models.ImageField(upload_to='profiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif']), inner_circle.models.validate_image_size]),
        ),
    ]
