# Generated by Django 6.0.4 on 2026-04-28 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner_circle', '0006_category_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='nombre',
            field=models.CharField(choices=[('Camisas', 'Camisas'), ('Camisetas', 'Camisetas'), ('Polos', 'Polos'), ('Pantalones', 'Pantalones'), ('Jeans', 'Jeans'), ('Sudaderas', 'Sudaderas'), ('Jerseis', 'Jerseis'), ('Chaquetones', 'Chaquetones')], default='Camisetas'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inner_circle.category'),
        ),
    ]
