# Generated by Django 6.0.4 on 2026-04-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inner_circle', '0006_user_friends'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('sender', 'recibidor2')},
        ),
    ]
