# Generated by Django 6.0.4 on 2026-05-02 16:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner_circle', '0007_add_product_soft_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(choices=[('fake_product', 'Producto falso/no auténtico'), ('never_received', 'Nunca llegó'), ('damage', 'Llegó dañado'), ('not_as_described', 'No corresponde a descripción')], max_length=50)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('RESPONDIDO', 'Vendedor respondió'), ('RESUELTO', 'Resuelto')], default='ABIERTO', max_length=20)),
                ('comprador_evidence', models.FileField(blank=True, null=True, upload_to='disputes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'webp'])])),
                ('vendedor_response', models.TextField(blank=True, null=True)),
                ('vendedor_evidence', models.FileField(blank=True, null=True, upload_to='disputes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'webp'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('refund_processed', models.BooleanField(default=False)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_buyer', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_seller', to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='inner_circle.venta')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
