# Generated by Django 6.0.4 on 2026-05-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner_circle', '0008_dispute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tipo',
            field=models.CharField(choices=[('mensaje', 'Nuevo mensaje'), ('venta', 'Nueva venta'), ('resena', 'Nueva reseña'), ('amistad', 'Solicitud de amistad'), ('dispute', 'Reclamación')], max_length=20),
        ),
    ]
