# Generated by Django 6.0.4 on 2026-05-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner_circle', '0009_alter_notification_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto - Esperando respuesta del vendedor'), ('RESPONDIDO', 'Respondido - Esperando decisión del admin'), ('REEMBOLSADO', 'Reembolsado - Comprador gana (refund)'), ('RECHAZADO', 'Rechazado - Vendedor gana (sin refund)')], default='ABIERTO', max_length=20),
        ),
    ]
