# Generated by Django 6.0.4 on 2026-05-04 18:46

import django.core.validators
import django.db.models.deletion
import inner_circle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner_circle', '0010_alter_dispute_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_prod',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif']), inner_circle.models.validate_image_size]),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif']), inner_circle.models.validate_image_size])),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inner_circle.product')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
