# Generated by Django 5.2.13 on 2026-05-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inner_circle', '0012_alter_blockeduser_id_alter_category_id_and_more'),
    ]

    operations = [
    ]
